SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE DOWNLOAD;
\! echo Cleared DOWNLOAD table
TRUNCATE TABLE MODIFICATION;
\! echo Cleared MODIFICATION table
TRUNCATE TABLE FILE;
\! echo Cleared FILE table
\! echo done!
SET FOREIGN_KEY_CHECKS = 1;

