[mgr]
show_hidden = true
ratio = [1, 2, 5]
sort_by = "btime"

[[plugin.prepend_fetchers]]
id   = "git"
url = "*"
run  = "git"
group = "file"

[[plugin.prepend_fetchers]]
id   = "git"
url = "*/"
run  = "git"
group = "folder"
