# Gruvbox dark by Dajonaga [ background = "default" to enjoy terminal transparency ]
[theme]
#background = "#282828"
background = "default"
primary = "#EBDBB2"
secondary = "#D5C4A1"
title = "#D65D0E"
playing = "#B16286"
playing_selected = "#458588"
playing_bg = "#1D2021"
highlight = "#D79921"
highlight_bg = "#1D2021"
error = "#FBF1C7"
error_bg = "#CC241D"
statusbar = "#282828"
statusbar_progress = "#689D6A"
statusbar_bg = "#98971A"
cmdline = "#1D2021"
cmdline_bg = "#FE8019"
search_match = "#fabd2f"

[keybindings]
"h" = "move left 1"
"j" = "move down 1"
"k" = "move up 1"
"l" = "move right 1"
"Shift+h" = "seek -10000"
"Shift+j" = "voldown"
"Shift+k" = "volup"
"Shift+l" = "seek 10000"

"n" = "next"
"Shift+n" = "previous"

"Shift+g" = "move top"
"gg" = "move gottom"

"?" = "help"
"-" = "back"

"r" = "repeat"
"Shift+r" = "shuffle"

"Shift+q" = "quit"
"o" = "open selected"
"Shift+o" = "open current"

"/" = "focus search"

"a" = "goto artist"
"Shift+a" = "goto album"

"Shift+y" = "share current"
"Shift+d" = "share selected"
