# Base16-black-metal-gorgoroth
[theme]
background = "#000000"
primary = "#c1c1c1"
secondary = "#999999"
title = "#5f8787"
playing = "#9b8d7f"
playing_selected = "#8c7f70"
playing_bg = "#222222"
highlight = "#888888"
highlight_bg = "#222222"
error = "#aaaaaa"
error_bg = "#444444"
statusbar = "#121212"
statusbar_progress = "#999999"
statusbar_bg = "#5f8787"
cmdline = "#222222"
cmdline_bg = "#999999"
search_match = "#c1c1c1"

[keybindings]
"h" = "move left 1"
"j" = "move down 1"
"k" = "move up 1"
"l" = "move right 1"
"Ctrl+d" = "move down 5"
"Ctrl+u" = "move up 5"
"Shift+h" = "seek -10000"
"Shift+j" = "voldown"
"Shift+k" = "volup"
"Shift+l" = "seek 10000"

"n" = "next"
"Shift+n" = "previous"

"Shift+g" = "move bottom"
"gg" = "move top"

"?" = "help"
"-" = "back"

"r" = "repeat"
"Shift+r" = "shuffle"

"Shift+q" = "quit"
"o" = "open selected"
"Shift+o" = "open current"

"/" = "focus search"

"a" = "goto artist"
"Shift+a" = "goto album"

"Shift+y" = "share current"
"Shift+d" = "share selected"
