vim.cmd([[set background=dark]])
vim.cmd([[let g:gruvbox_material_background = "hard"]])
vim.cmd([[let g:gruvbox_material_diagnostic_virtual_text = "colored"]])
vim.cmd([[let g:gruvbox_material_transparent_background = 1]])
vim.cmd([[let g:gruvbox_material_float_style = "dim"]])
vim.cmd([[colorscheme gruvbox-material]])
