#!/bin/bash
set -euo pipefail

# usually lives on nas as a cronjob

RCLONE_REMOTE="aws-backups:gargantua-bucket"

FOLDERS=(
  "/gargantua/endurance"
  "/gargantua/pimaster"
  "/gargantua/shows"
  "/gargantua/movies"
)

for folder in "${FOLDERS[@]}"; do
  folder_name=$(basename "$folder")

  echo "🔁 Syncing ${folder} → ${RCLONE_REMOTE}/${folder_name}/"

  rclone sync "$folder" "${RCLONE_REMOTE}/${folder_name}/" \
     --s3-storage-class INTELLIGENT_TIERING \
     --transfers=4 \
     --checkers=8 \
     --delete-after \
     --copy-links \
     --keep-dirlinks
done

echo "✅ All folders synced successfully!"
