#!/usr/bin/bash

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Not running as root"
    exit
fi

if [[ $1 -eq 0 ]]; then
    tuned-adm profile laptop-battery-powersave
    powertop --auto-tune
else
    tuned-adm profile balanced
fi

