#!/usr/bin/env bash

sudo rsync -avzhP --update --delete \
    --exclude '**/*[cC][aA][cC][hH][eE]*' \
    --exclude 'Downloads' \
    --exclude '.bun' \
    --exclude '.docker' \
    --exclude '.cache' \
    --exclude '.cargo' \
    --exclude '.mozilla' \
    --exclude '.rustup' \
    --exclude 'go' \
    --exclude 'node_modules' \
    --exclude 'target' \
    --exclude 'Unity' \
    --exclude '.local' \
    /home/maneesh /run/media/veracrypt1/
