#!/usr/bin/bash

sudo cp -r /etc/udev/rules.d \
    ~/dotfiles/linux/

cp -r ~/.config/nvim \
    ~/.config/ghostty \
    ~/.tmux.conf \
    ~/.config/yazi \
    ~/.config/ncspot \
    ~/.bashrc \
    ~/dotfiles/

cp -r ~/.config/sway \
    ~/.config/swaylock \
    ~/.config/swaync \
    ~/.config/waybar \
    ~/.config/rofi \
    ~/.config/swappy \
    ~/.config/pcmanfm \
    ~/.config/scripts \
    ~/.config/zathura \
    ~/.config/wireplumber \
    ~/.config/fontconfig \
    ~/dotfiles/linux/
