#!/usr/bin/bash

sudo cp -r ~/.config/nvim \
    ~/.config/ghostty \
    ~/.config/tmux-sessionizer \
    ~/.config/yazi \
    ~/.config/hypr \
    ~/.config/swappy \
    ~/.config/tofi \
    ~/.config/zathura \
    ~/.config/wireplumber \
    ~/.config/systemd \
    ~/.config/scripts \
    ~/.config/dunst \
    ~/.zshrc \
    ~/.tmux.conf \
    ~/.icons \
    ~/.themes \
    ~/dotfiles/
