require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.gitsigns"
require "user.colorscheme"
require "user.autopairs"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.comment"
require "user.nvim-tree"
require "user.lualine"
require "user.dap"
require('dap-python').setup('~/.virtualenvs/debugpy/bin/python')
